version: '3.8'
services:
 rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq
    command: rabbitmq-server 
    ports:
     - 5672:5672
     - 15672:15672
    restart: always
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
 example01:
    image: quarkus/example-jvm:latest
    container_name: example01
    ports:
     - 8080:8080